name: Build iOS App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install dependencies
      working-directory: ./app_ghichu
      run: flutter pub get

    - name: Build XCArchive
      working-directory: ./app_ghichu
      run: flutter build ipa --release --no-codesign

    - name: Export IPA from XCArchive
      working-directory: ./app_ghichu
      # THÊM CÁC THAM SỐ VÀO CUỐI LỆNH
      run: xcodebuild -exportArchive -archivePath build/ios/archive/Runner.xcarchive -exportPath build/ios/ipa -exportOptionsPlist ios/ExportOptions.plist CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app_ghichu/build/ios/ipa/*.ipa