name: Build iOS App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install dependencies
      working-directory: ./app_ghichu
      run: flutter pub get

    - name: Build IPA
      working-directory: ./app_ghichu
      run: flutter build ipa --release --no-codesign

    # === BƯỚC GỠ LỖI MỚI ===
    - name: List build output
      working-directory: ./app_ghichu
      run: ls -R build
    # ========================

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app_ghichu/build/ios/ipa/*.ipa