name: Build iOS App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install dependencies
      # Chỉ định thư mục làm việc cho bước này
      working-directory: ./app_ghichu
      run: flutter pub get

    - name: Build IPA
      # Chỉ định thư mục làm việc cho bước này nữa
      working-directory: ./app_ghichu
      run: flutter build ipa --release --no-codesign

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        # Đường dẫn phải tính từ gốc, nên phải có app_ghichu/
        path: app_ghichu/build/ios/ipa/*.ipa